[book]
title = "SEiN Knowledge Hub"
authors = ["SEiN"]
description = "This is the space for collecting information regarding this entire project."

[rust]
edition = "2018"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2