window.SEIN_SEARCH_INDEX = [
  {
    lang: "en",
    title: "Main page",
    url: "index.html",
    category: "Knowledge Hub",
    summary: "General idea of the SEiN Knowledge Hub and its wiki-style information structure.",
    keywords: "knowledge hub main page wiki social issues expansion categories",
  },
  {
    lang: "en",
    title: "How to research a social issue",
    url: "research-social-issues.html",
    category: "Some Hows",
    summary: "A practical method for researching social issues with source mapping, systems mapping, field conversations, and references.",
    keywords: "research social issue method sources evidence field notes policy context source mapping systems mapping evaluation references",
  },
  {
    lang: "en",
    title: "How to have hope to help",
    url: "how-to-have-hope-to-help.html",
    category: "Some Hows",
    summary: "A reflective method for turning from self-protection toward reality, others, and hope-filled help.",
    keywords: "hope help heart outward motivated reasoning cognitive dissonance self justification reality others God service care",
  },
  {
    lang: "en",
    title: "Homelessness in Berlin",
    url: "homelessness-berlin.html",
    category: "Homelessness",
    summary: "Overview of homelessness support routes, emergency help, and Berlin resource orientation.",
    keywords: "homelessness Berlin shelter emergency Kaeltehilfe housing support Soziale Wohnhilfe resource directory",
  },
  {
    lang: "en",
    title: "How to help Berlin homeless people",
    url: "homelessness-how-to-help.html",
    category: "Homelessness",
    summary: "Consent-based guidance for helping people experiencing homelessness in Berlin.",
    keywords: "help volunteer donate consent outreach food water emergency respectful support",
  },
  {
    lang: "en",
    title: "Organizations helping Berlin homeless people",
    url: "homelessness-organizations-berlin.html",
    category: "Homelessness",
    summary: "A starter list of Berlin social organizations and services working with homelessness.",
    keywords: "organizations Berlin homeless social services Stadtmission Caritas Diakonie Berliner Kaeltehilfe Teen Challenge Berliner Help Stiftung Salvation Army Heilsarmee",
  },
  {
    lang: "en",
    title: "Homelessness policies in Germany",
    url: "homelessness-policies-germany.html",
    category: "Homelessness",
    summary: "Selected German homelessness policy developments and public strategy context from the last decade.",
    keywords: "Germany homelessness policy national action plan housing first social law statistics BAG W",
  },
  {
    lang: "en",
    title: "Knowledge Hub version log",
    url: "knowledge-hub-version-log.html",
    category: "Knowledge Hub development",
    summary: "Numbered record of Knowledge Hub revisions, timestamps, areas, and updated content.",
    keywords: "version log revision timestamp update development changelog knowledge hub",
  },
  {
    lang: "en",
    title: "Knowledge Hub next steps",
    url: "knowledge-hub-next-steps.html",
    category: "Knowledge Hub development",
    summary: "Possible improvements and next development steps for the Knowledge Hub website.",
    keywords: "next steps improvements development roadmap future categories search translation labels source sources issues",
  },
  {
    lang: "en",
    title: "Imprint",
    url: "imprint.html",
    category: "Legal",
    summary: "Provider information and required operator details for the SEiN Knowledge Hub.",
    keywords: "imprint impressum provider legal notice operator contact DDG MStV",
  },
  {
    lang: "en",
    title: "Privacy Policy",
    url: "privacy.html",
    category: "Legal",
    summary: "Privacy information for the static GitHub Pages website and external links.",
    keywords: "privacy policy data protection GDPR GitHub Pages IP address logs local storage",
  },
  {
    lang: "en",
    title: "License",
    url: "license.html",
    category: "Legal",
    summary: "Reuse terms for Knowledge Hub content and website code.",
    keywords: "license licence CC BY 4.0 MIT reuse attribution code content",
  },
  {
    lang: "de",
    title: "Startseite",
    url: "index.de.html",
    category: "Knowledge Hub",
    summary: "Grundidee des SEiN Knowledge Hub und seiner wikiartigen Informationsstruktur.",
    keywords: "Knowledge Hub Startseite Wiki soziale Themen Erweiterung Kategorien",
  },
  {
    lang: "de",
    title: "Wie man ein soziales Thema recherchiert",
    url: "research-social-issues.de.html",
    category: "Einige Wie-Fragen",
    summary: "Eine praktische Methode zur Recherche sozialer Themen mit Quellenkartierung, Systemkartierung, Feldgesprächen und Referenzen.",
    keywords: "Recherche soziales Thema Methode Quellen Evidenz Feldnotizen Politik Kontext Quellenkartierung Systemkartierung Evaluation Referenzen",
  },
  {
    lang: "de",
    title: "Wie man Hoffnung behält, um zu helfen",
    url: "how-to-have-hope-to-help.de.html",
    category: "Einige Wie-Fragen",
    summary: "Eine reflektierende Methode, um sich von Selbstschutz hin zu Wirklichkeit, anderen Menschen und hoffnungsvoller Hilfe zu wenden.",
    keywords: "Hoffnung helfen Herz nach außen motiviertes Schlussfolgern kognitive Dissonanz Selbstrechtfertigung Wirklichkeit andere Gott Dienst Fürsorge",
  },
  {
    lang: "de",
    title: "Wohnungslosigkeit in Berlin",
    url: "homelessness-berlin.de.html",
    category: "Wohnungslosigkeit",
    summary: "Überblick über Unterstützungswege, Soforthilfe und Berliner Ressourcen zur Wohnungslosigkeit.",
    keywords: "Wohnungslosigkeit Berlin Unterkunft Notfall Kältehilfe Wohnhilfe Unterstützung Ressourcenverzeichnis",
  },
  {
    lang: "de",
    title: "Wie man wohnungslosen Menschen in Berlin hilft",
    url: "homelessness-how-to-help.de.html",
    category: "Wohnungslosigkeit",
    summary: "Zustimmungsbasierte Hinweise zur Hilfe für wohnungslose Menschen in Berlin.",
    keywords: "helfen freiwillig spenden Zustimmung Streetwork Essen Wasser Notfall respektvolle Unterstützung",
  },
  {
    lang: "de",
    title: "Organisationen für wohnungslose Menschen in Berlin",
    url: "homelessness-organizations-berlin.de.html",
    category: "Wohnungslosigkeit",
    summary: "Eine Startliste Berliner Organisationen und Dienste im Bereich Wohnungslosigkeit.",
    keywords: "Organisationen Berlin wohnungslos soziale Dienste Stadtmission Caritas Diakonie Berliner Kältehilfe Teen Challenge Berliner Help Stiftung Salvation Army Heilsarmee",
  },
  {
    lang: "de",
    title: "Politik zu Wohnungslosigkeit in Deutschland",
    url: "homelessness-policies-germany.de.html",
    category: "Wohnungslosigkeit",
    summary: "Ausgewählte politische Entwicklungen zu Wohnungslosigkeit in Deutschland aus den letzten Jahren.",
    keywords: "Deutschland Wohnungslosigkeit Politik Nationaler Aktionsplan Housing First Sozialrecht Statistik BAG W",
  },
  {
    lang: "de",
    title: "Versionsprotokoll des Knowledge Hub",
    url: "knowledge-hub-version-log.de.html",
    category: "Entwicklung des Knowledge Hub",
    summary: "Nummeriertes Protokoll der Revisionen, Zeitstempel, Bereiche und aktualisierten Inhalte.",
    keywords: "Versionsprotokoll Revision Zeitstempel Aktualisierung Entwicklung Changelog Knowledge Hub",
  },
  {
    lang: "de",
    title: "Nächste Schritte des Knowledge Hub",
    url: "knowledge-hub-next-steps.de.html",
    category: "Entwicklung des Knowledge Hub",
    summary: "Mögliche Verbesserungen und nächste Entwicklungsschritte für die Knowledge-Hub-Website.",
    keywords: "nächste Schritte Verbesserungen Entwicklung Roadmap zukünftige Kategorien Suche Übersetzung Labels Quelle Quellen Issues",
  },
  {
    lang: "de",
    title: "Impressum",
    url: "imprint.de.html",
    category: "Rechtliches",
    summary: "Anbieterinformationen und erforderliche Betreiberdaten für den SEiN Knowledge Hub.",
    keywords: "Impressum Anbieterkennzeichnung rechtlicher Hinweis Betreiber Kontakt DDG MStV",
  },
  {
    lang: "de",
    title: "Datenschutz",
    url: "privacy.de.html",
    category: "Rechtliches",
    summary: "Datenschutzhinweise für die statische GitHub-Pages-Website und externe Links.",
    keywords: "Datenschutz Datenschutzerklärung DSGVO GitHub Pages IP-Adresse Logs local storage",
  },
  {
    lang: "de",
    title: "Lizenz",
    url: "license.de.html",
    category: "Rechtliches",
    summary: "Nutzungsbedingungen für Inhalte und Website-Code des Knowledge Hub.",
    keywords: "Lizenz CC BY 4.0 MIT Wiederverwendung Namensnennung Code Inhalt",
  },
];
