window.SEIN_SEARCH_INDEX = [
  {
    lang: "en",
    title: "Main page",
    url: "index.html",
    category: "Knowledge Hub",
    summary: "General idea of the SEiN Knowledge Hub and its wiki-style information structure.",
    keywords: "knowledge hub main page wiki social issues expansion categories",
  },
  {
    lang: "en",
    title: "How to research a social issue",
    url: "research-social-issues.html",
    category: "Research method",
    summary: "A practical method for researching social issues with sources, context, and revision notes.",
    keywords: "research social issue method sources evidence field notes policy context",
  },
  {
    lang: "en",
    title: "Homelessness in Berlin",
    url: "homelessness-berlin.html",
    category: "Homelessness",
    summary: "Overview of homelessness support routes, emergency help, and Berlin resource orientation.",
    keywords: "homelessness Berlin shelter emergency Kaeltehilfe housing support Soziale Wohnhilfe resource directory",
  },
  {
    lang: "en",
    title: "How to help Berlin homeless people",
    url: "homelessness-how-to-help.html",
    category: "Homelessness",
    summary: "Consent-based guidance for helping people experiencing homelessness in Berlin.",
    keywords: "help volunteer donate consent outreach food water emergency respectful support",
  },
  {
    lang: "en",
    title: "Organizations helping Berlin homeless people",
    url: "homelessness-organizations-berlin.html",
    category: "Homelessness",
    summary: "A starter list of Berlin social organizations and services working with homelessness.",
    keywords: "organizations Berlin homeless social services Stadtmission Caritas Diakonie Berliner Kaeltehilfe",
  },
  {
    lang: "en",
    title: "Homelessness policies in Germany",
    url: "homelessness-policies-germany.html",
    category: "Homelessness",
    summary: "Selected German homelessness policy developments and public strategy context from the last decade.",
    keywords: "Germany homelessness policy national action plan housing first social law statistics BAG W",
  },
  {
    lang: "en",
    title: "Knowledge Hub version log",
    url: "knowledge-hub-version-log.html",
    category: "Knowledge Hub development",
    summary: "Numbered record of Knowledge Hub revisions, timestamps, areas, and updated content.",
    keywords: "version log revision timestamp update development changelog knowledge hub",
  },
  {
    lang: "en",
    title: "Knowledge Hub next steps",
    url: "knowledge-hub-next-steps.html",
    category: "Knowledge Hub development",
    summary: "Possible improvements and next development steps for the Knowledge Hub website.",
    keywords: "next steps improvements development roadmap future categories search translation labels source sources issues",
  },
  {
    lang: "de",
    title: "Startseite",
    url: "index.de.html",
    category: "Knowledge Hub",
    summary: "Grundidee des SEiN Knowledge Hub und seiner wikiartigen Informationsstruktur.",
    keywords: "Knowledge Hub Startseite Wiki soziale Themen Erweiterung Kategorien",
  },
  {
    lang: "de",
    title: "Wie man ein soziales Thema recherchiert",
    url: "research-social-issues.de.html",
    category: "Recherchemethode",
    summary: "Eine praktische Methode zur Recherche sozialer Themen mit Quellen, Kontext und Revisionsnotizen.",
    keywords: "Recherche soziales Thema Methode Quellen Evidenz Feldnotizen Politik Kontext",
  },
  {
    lang: "de",
    title: "Wohnungslosigkeit in Berlin",
    url: "homelessness-berlin.de.html",
    category: "Wohnungslosigkeit",
    summary: "Überblick über Unterstützungswege, Soforthilfe und Berliner Ressourcen zur Wohnungslosigkeit.",
    keywords: "Wohnungslosigkeit Berlin Unterkunft Notfall Kältehilfe Wohnhilfe Unterstützung Ressourcenverzeichnis",
  },
  {
    lang: "de",
    title: "Wie man wohnungslosen Menschen in Berlin hilft",
    url: "homelessness-how-to-help.de.html",
    category: "Wohnungslosigkeit",
    summary: "Zustimmungsbasierte Hinweise zur Hilfe für wohnungslose Menschen in Berlin.",
    keywords: "helfen freiwillig spenden Zustimmung Streetwork Essen Wasser Notfall respektvolle Unterstützung",
  },
  {
    lang: "de",
    title: "Organisationen für wohnungslose Menschen in Berlin",
    url: "homelessness-organizations-berlin.de.html",
    category: "Wohnungslosigkeit",
    summary: "Eine Startliste Berliner Organisationen und Dienste im Bereich Wohnungslosigkeit.",
    keywords: "Organisationen Berlin wohnungslos soziale Dienste Stadtmission Caritas Diakonie Berliner Kältehilfe",
  },
  {
    lang: "de",
    title: "Politik zu Wohnungslosigkeit in Deutschland",
    url: "homelessness-policies-germany.de.html",
    category: "Wohnungslosigkeit",
    summary: "Ausgewählte politische Entwicklungen zu Wohnungslosigkeit in Deutschland aus den letzten Jahren.",
    keywords: "Deutschland Wohnungslosigkeit Politik Nationaler Aktionsplan Housing First Sozialrecht Statistik BAG W",
  },
  {
    lang: "de",
    title: "Versionsprotokoll des Knowledge Hub",
    url: "knowledge-hub-version-log.de.html",
    category: "Entwicklung des Knowledge Hub",
    summary: "Nummeriertes Protokoll der Revisionen, Zeitstempel, Bereiche und aktualisierten Inhalte.",
    keywords: "Versionsprotokoll Revision Zeitstempel Aktualisierung Entwicklung Changelog Knowledge Hub",
  },
  {
    lang: "de",
    title: "Nächste Schritte des Knowledge Hub",
    url: "knowledge-hub-next-steps.de.html",
    category: "Entwicklung des Knowledge Hub",
    summary: "Mögliche Verbesserungen und nächste Entwicklungsschritte für die Knowledge-Hub-Website.",
    keywords: "nächste Schritte Verbesserungen Entwicklung Roadmap zukünftige Kategorien Suche Übersetzung Labels Quelle Quellen Issues",
  },
];
